name: Cleanup PR preview

on:
  pull_request:
    types:
      - closed

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: deploy-${{ github.event.pull_request.number }}
  cancel-in-progress: true

env:
  BASE_URL: /${{ github.event.pull_request.number }}

jobs:
  deploy:
    environment:
      name: gh-pages
      url: https://reproducible-research.polymtl.ca${{ env.BASE_URL }}

    runs-on: ubuntu-latest

    steps:
      - name: Create empty build
        run: rm -rf _build/ && mkdir -p _build/html/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453
          # Version 4.1.0, pinned by commit hash since it's a third-party action
          # We use peaceiris/actions-gh-pages instead of actions/deploy-pages
          # because of the `destination_dir` option, which lets us keep the
          # files from other deployments in other sub-directories.
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/html/
          destination_dir: ./${{ env.BASE_URL }}
