name: Tests

on:
  pull_request:
  push:
    branches:
      - '**'

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: "3.14"
      - run: pip install pytest pyyaml
      - run: python3 -m pytest tests/ -v
